### ISSUE TITLE
RuntimeError: [Open3D WARNING] [ViewControl]

### ISSUE THREAD

**Issue by VMohinder** [mauriceqch/pcc_geo_cnn_v2#5]
Problem running 

python ut_run_render.py ev_experiment.yml.

RuntimeError: [Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.

**Comment by mauriceqch** [comment]
Can you provide the full log output ?

**Comment by VMohinder** [comment]
python ut_run_render.py ev_experiment.yml
INFO - 2021-03-23 12:01:21,373 - ut_run_render - Gathering camera params and paths
INFO - 2021-03-23 12:01:21,670 - ut_run_render - Loading camera parameters for loot_vox10_1200 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/loot_vox10_1200/camera_params.json
INFO - 2021-03-23 12:01:21,947 - ut_run_render - Loading camera parameters for redandblack_vox10_1550 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/redandblack_vox10_1550/camera_params.json
INFO - 2021-03-23 12:01:22,260 - ut_run_render - Loading camera parameters for longdress_vox10_1300 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/longdress_vox10_1300/camera_params.json
INFO - 2021-03-23 12:01:22,656 - ut_run_render - Loading camera parameters for soldier_vox10_0690 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/soldier_vox10_0690/camera_params.json
INFO - 2021-03-23 12:01:22,656 - ut_run_render - Starting rendering
INFO - 2021-03-23 12:01:22,656 - ut_run_render - Rendering loot_vox10_1200
INFO - 2021-03-23 12:01:22,667 - ut_run_render - Loaded img loot_vox10_1200 with (967, 316, 3) with trim bbox [352, 18, 668, 985]
INFO - 2021-03-23 12:01:22,667 - ut_run_render - Rendering redandblack_vox10_1550
INFO - 2021-03-23 12:01:22,675 - ut_run_render - Loaded img redandblack_vox10_1550 with (981, 437, 3) with trim bbox [294, 18, 731, 999]
INFO - 2021-03-23 12:01:22,675 - ut_run_render - Rendering longdress_vox10_1300
INFO - 2021-03-23 12:01:22,684 - ut_run_render - Loaded img longdress_vox10_1300 with (983, 374, 3) with trim bbox [335, 26, 709, 1009]
INFO - 2021-03-23 12:01:22,684 - ut_run_render - Rendering soldier_vox10_0690
INFO - 2021-03-23 12:01:22,693 - ut_run_render - Loaded img soldier_vox10_0690 with (999, 418, 3) with trim bbox [325, 5, 743, 1004]
INFO - 2021-03-23 12:01:22,693 - ut_run_render - Rendering visual comparisons
INFO - 2021-03-23 12:01:22,693 - ut_run_render - soldier_c4ws_tris_hbr soldier_vox10_0690
INFO - 2021-03-23 12:01:22,927 - ut_run_render - Loading soldier_vox10_0690_c4ws_1em04
{
    "d1_mae": 0.338737,
    "d1_mse": 0.365347,
    "d1_psnr": 69.3417,
    "d2_mse": 0.208163,
    "d2_psnr": 71.7847,
    "input_point_count": 1089091,
    "pos_bits_per_input_point": 0.19396726260707323,
    "pos_total_size_in_bytes": 26406
}
INFO - 2021-03-23 12:01:23,182 - ut_run_render - Loading soldier_vox10_0690_tris_r05
{
    "color_bits_per_input_point": 0.13429180848983235,
    "color_bits_per_output_point": 0.134292,
    "color_bitstream_size_in_bytes": 18282,
    "d1_mae": 0.736072,
    "d1_mse": 0.812265,
    "d1_psnr": 65.8717,
    "d2_mse": 0.392731,
    "d2_psnr": 69.0278,
    "input_point_count": 1089091,
    "pos_bits_per_input_point": 0.18767210453488276,
    "pos_bits_per_output_point": 0.187672,
    "pos_bitstream_size_in_bytes": 25549,
    "pos_total_size_in_bytes": 25549,
    "uncompressed_data_path": "/home/quachmau/data/datasets/mpeg_pcc/Static_Objects_and_Scenes/People/soldier_vox10_0690/soldier_vox10_0690.ply"
}
Traceback (most recent call last):
  File "ut_run_render.py", line 222, in <module>
    img = pc_to_img(pcd, camera_params)
  File "/utils/o3d.py", line 60, in pc_to_img
    raise RuntimeError(out)
RuntimeError: [Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.

**Comment by VMohinder** [comment]
python ut_run_render.py ev_experiment.yml
INFO - 2021-03-23 12:01:21,373 - ut_run_render - Gathering camera params and paths
INFO - 2021-03-23 12:01:21,670 - ut_run_render - Loading camera parameters for loot_vox10_1200 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/loot_vox10_1200/camera_params.json
INFO - 2021-03-23 12:01:21,947 - ut_run_render - Loading camera parameters for redandblack_vox10_1550 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/redandblack_vox10_1550/camera_params.json
INFO - 2021-03-23 12:01:22,260 - ut_run_render - Loading camera parameters for longdress_vox10_1300 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/longdress_vox10_1300/camera_params.json
INFO - 2021-03-23 12:01:22,656 - ut_run_render - Loading camera parameters for soldier_vox10_0690 and 80 dependent point clouds from /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/soldier_vox10_0690/camera_params.json
INFO - 2021-03-23 12:01:22,656 - ut_run_render - Starting rendering
INFO - 2021-03-23 12:01:22,656 - ut_run_render - Rendering loot_vox10_1200
INFO - 2021-03-23 12:01:22,667 - ut_run_render - Loaded img loot_vox10_1200 with (967, 316, 3) with trim bbox [352, 18, 668, 985]
INFO - 2021-03-23 12:01:22,667 - ut_run_render - Rendering redandblack_vox10_1550
INFO - 2021-03-23 12:01:22,675 - ut_run_render - Loaded img redandblack_vox10_1550 with (981, 437, 3) with trim bbox [294, 18, 731, 999]
INFO - 2021-03-23 12:01:22,675 - ut_run_render - Rendering longdress_vox10_1300
INFO - 2021-03-23 12:01:22,684 - ut_run_render - Loaded img longdress_vox10_1300 with (983, 374, 3) with trim bbox [335, 26, 709, 1009]
INFO - 2021-03-23 12:01:22,684 - ut_run_render - Rendering soldier_vox10_0690
INFO - 2021-03-23 12:01:22,693 - ut_run_render - Loaded img soldier_vox10_0690 with (999, 418, 3) with trim bbox [325, 5, 743, 1004]
INFO - 2021-03-23 12:01:22,693 - ut_run_render - Rendering visual comparisons
INFO - 2021-03-23 12:01:22,693 - ut_run_render - soldier_c4ws_tris_hbr soldier_vox10_0690
INFO - 2021-03-23 12:01:22,927 - ut_run_render - Loading soldier_vox10_0690_c4ws_1em04
{
    "d1_mae": 0.338737,
    "d1_mse": 0.365347,
    "d1_psnr": 69.3417,
    "d2_mse": 0.208163,
    "d2_psnr": 71.7847,
    "input_point_count": 1089091,
    "pos_bits_per_input_point": 0.19396726260707323,
    "pos_total_size_in_bytes": 26406
}
INFO - 2021-03-23 12:01:23,182 - ut_run_render - Loading soldier_vox10_0690_tris_r05
{
    "color_bits_per_input_point": 0.13429180848983235,
    "color_bits_per_output_point": 0.134292,
    "color_bitstream_size_in_bytes": 18282,
    "d1_mae": 0.736072,
    "d1_mse": 0.812265,
    "d1_psnr": 65.8717,
    "d2_mse": 0.392731,
    "d2_psnr": 69.0278,
    "input_point_count": 1089091,
    "pos_bits_per_input_point": 0.18767210453488276,
    "pos_bits_per_output_point": 0.187672,
    "pos_bitstream_size_in_bytes": 25549,
    "pos_total_size_in_bytes": 25549,
    "uncompressed_data_path": "/home/quachmau/data/datasets/mpeg_pcc/Static_Objects_and_Scenes/People/soldier_vox10_0690/soldier_vox10_0690.ply"
}
Traceback (most recent call last):
  File "ut_run_render.py", line 222, in <module>
    img = pc_to_img(pcd, camera_params)
  File "/media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/src/utils/o3d.py", line 60, in pc_to_img
    raise RuntimeError(out)
RuntimeError: [Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.

**Comment by VMohinder** [comment]
Great work, by the way.

**Comment by mauriceqch** [comment]
> Great work, by the way.

Thanks! Happy to know that it is useful to you.

It seems there may be a mismatch between the camera parameters in the downloaded experimental data and your screen resolution.
Can you try removing the following files and rerunning the script ?

```
rm **/camera_params.json
rm **/*.ply.png
```

This will remove all point cloud renders and camera parameters.
Then, upon rerunning the script, you should be able to set your desired camera viewpoint/parameters for each point cloud (close the window when you are finished setting up a point cloud).

**Comment by VMohinder** [comment]
Hi, Maurice, it worked! Thank you for insight.
