### ISSUE TITLE
Test Conditions for Trisoup in TMC13v12

### ISSUE THREAD

**Issue by VMohinder** [mauriceqch/pcc_geo_cnn_v2#6]
In TMC13v12, trisoup has only r01 to r04 rates. There are no configuration files for r05 and r06 anymore.

Just to make the scripts run, I added the following function:

<pre>
def set_tmc13_rate_limit(mpeg_mode):
    if mpeg_mode['label'] == 'G-PCC trisoup':
        return 4
    return 6
</pre>

And then, when needed:
<pre>
rSup = set_tmc13_rate_limit(mpeg_mode)
for rate in rates[0:rSup]:
          Code
</pre>

Not very elegant, but solved the problem for the G-PCC experiments (python mp_run.py ev_experiment.yml)

Running experiments using the models (python ev_run_experiment.py ev_experiment.yml --num_parallel 8) still has some issues regarding trisoup rates.

python ev_run_experiment.py ev_experiment.yml --num_parallel 8
2021-03-23 12:44:27.065 INFO ev_run_experiment - <module>: Starting our method's experiments
  0%|                                                                                                                                    | 0/136 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "ev_run_experiment.py", line 91, in <module>
    parallel_process(run_experiment, params, args.num_parallel)
  File "/media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/src/utils/parallel_process.py", line 41, in parallel_process
    raise RuntimeError(f'{" ".join([shlex.quote(x) for x in p.args])} returned with code {p.returncode}\n{logs}')
RuntimeError: python ev_experiment.py --output_dir /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/soldier_vox10_0690/c2/1.00e-05 --model_dir /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/pcc_geo_cnn_v2/models/c2/1.00e-05 --model_config c2 --opt_metrics d1_mse d2_mse --max_deltas inf --pc_name soldier_vox10_0690 --pcerror_path /media/bizon/DATA02_4TB/MPEG/mpeg-pcc-dmetric/test/pc_error_d --pcerror_cfg_path /media/bizon/DATA02_4TB/MPEG/TMC13/mpeg-pcc-tmc13/cfg/trisoup-predlift/lossy-geom-lossy-attrs/soldier_vox10_0690/r06/pcerror.cfg --input_pc /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/data/Static_Objects_and_Scenes/People/soldier_vox10_0690/soldier_vox10_0690.ply --input_norm /media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/data/Static_Objects_and_Scenes/People/soldier_vox10_0690/soldier_vox10_0690_n.ply --fixed_threshold returned with code 1
Traceback (most recent call last):
  File "ev_experiment.py", line 194, in <module>
    args.fixed_threshold, args.no_merge_coding, args.num_parallel, args.no_stream_redirection)
  File "ev_experiment.py", line 55, in run_experiment
    assert_exists(f)
  File "/media/bizon/DATA01_1TB/MachineLearning/PointCloudCompression/pcc_geo_cnn_v2/src/utils/experiment.py", line 8, in assert_exists
    assert os.path.exists(filepath), f'{filepath} not found'
AssertionError: /media/bizon/DATA02_4TB/MPEG/TMC13/mpeg-pcc-tmc13/cfg/trisoup-predlift/lossy-geom-lossy-attrs/soldier_vox10_0690/r06/pcerror.cfg not found

Probably this line of code in _ev_run_experiment.py_ must be updated:

<pre>

pcerror_cfg_path = f'{MPEG_TMC13_DIR}/cfg/{pcerror_mpeg_mode}/{cfg_name}/r06/pcerror.cfg'

</pre>

**Comment by mauriceqch** [comment]
Thank you!

This line
```
pcerror_cfg_path = f'{MPEG_TMC13_DIR}/cfg/{pcerror_mpeg_mode}/{cfg_name}/r06/pcerror.cfg
```
can probably be replaced by
```
pcerror_cfg_path = f'{MPEG_TMC13_DIR}/cfg/{pcerror_mpeg_mode}/{cfg_name}/r01/pcerror.cfg'
```
as the pcerror configurations seem to be the same for the rates of a single point cloud.

I'll keep this in mind for future updates.
